<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Super Admin Dashboard | TELE-CARE</title>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
	<style>
		:root{--red:#b31118;--red-dark:#8a000b;--teal:#006a61;--teal-light:#0d9488;--ink:#151c27;--muted:#718096;--line:rgba(21,28,39,.09);--canvas:#f7f9fb;--white:#fff;--green:#10b981}
		*{box-sizing:border-box}html,body{min-height:100%}body{margin:0;background:var(--canvas);color:var(--ink);font-family:'Inter',sans-serif;font-size:15px}a{color:inherit;text-decoration:none}button,input{font:inherit}
		.admin-shell{min-height:100vh;display:flex}.sidebar{width:260px;min-width:260px;background:var(--white);border-right:1px solid var(--line);display:flex;flex-direction:column;position:fixed;inset:0 auto 0 0;z-index:5}.brand{display:flex;align-items:center;gap:12px;padding:24px 22px 21px}.brand-mark{width:30px;height:30px;display:grid;place-items:center;border-radius:8px;color:#fff;background:var(--red);font-weight:800;font-size:18px;box-shadow:0 4px 10px rgba(179,17,24,.2)}.brand-name{font-size:14px;font-weight:800}.brand-role{display:block;color:#8a94a6;font-size:9px;letter-spacing:.04em;margin-top:3px}.sidebar-nav{padding:26px 12px}.nav-label{color:#9aa4b2;font-size:10px;font-weight:700;letter-spacing:.08em;margin:0 13px 11px;text-transform:uppercase}.nav-link{display:flex;align-items:center;gap:12px;padding:12px 13px;margin:3px 0;border-radius:6px;color:#50617a;font-size:13px;font-weight:500;transition:background .2s,color .2s}.nav-link svg{width:17px;height:17px;color:#8fa0b7;flex-shrink:0}.nav-link:hover{background:#fff3f3;color:var(--red)}.nav-link.active{background:var(--red);color:#fff;font-weight:700;box-shadow:0 5px 12px rgba(179,17,24,.14)}.nav-link.active svg{color:#fff}.nav-group{margin-top:25px}.sidebar-footer{margin-top:auto;padding:16px 22px;border-top:1px solid var(--line);color:#8793a5;font-size:11px}
		.main{margin-left:260px;min-width:0;flex:1;display:flex;flex-direction:column}.topbar{height:74px;flex-shrink:0;background:var(--white);border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 44px}.search{width:380px;position:relative}.search input{width:100%;border:1px solid #e2e7ed;border-radius:10px;padding:12px 15px 12px 42px;color:var(--ink);font-size:13px;outline:none}.search input:focus{border-color:var(--teal-light)}.search svg{position:absolute;left:14px;top:11px;width:18px;color:#9aa6b7}.top-actions{display:flex;align-items:center;gap:28px}.notification{position:relative;color:#5f6d81}.notification svg{width:21px}.notification b{position:absolute;top:-8px;right:-8px;min-width:15px;height:15px;border-radius:9px;background:var(--red);color:#fff;font-size:9px;text-align:center;line-height:15px}.profile{display:flex;align-items:center;gap:10px}.profile-avatar{width:32px;height:32px;display:grid;place-items:center;border-radius:50%;background:#101827;color:#fff;font-size:10px;font-weight:700}.profile strong{display:block;font-size:12px}.profile small{display:block;color:#8a94a6;font-size:10px;margin-top:2px}
		.content{flex:1;width:100%;max-width:none;margin:0;padding:36px 56px 56px;display:flex;flex-direction:column}
		.page-heading{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:30px}h1{margin:0 0 8px;font-size:26px;line-height:1.15}.subtitle{margin:0;color:var(--muted);font-size:13px}.date-note{color:#8a94a6;font-size:11px;text-align:right;line-height:1.5}.date-note strong{color:#64748b;display:block}
		.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:24px;margin-bottom:28px}.stat-card,.panel{background:var(--white);border:1px solid var(--line);border-radius:14px;box-shadow:0 3px 13px rgba(21,28,39,.035)}.stat-card{min-height:128px;padding:24px 26px;display:flex;align-items:center;gap:20px}.stat-icon{width:50px;height:50px;display:grid;place-items:center;border-radius:12px;flex-shrink:0}.stat-icon svg{width:24px;height:24px}.stat-icon.blue{color:#2f7fe7;background:#eef5ff}.stat-icon.teal{color:var(--teal);background:#eafbf7}.stat-icon.purple{color:#9347db;background:#f5edff}.stat-icon.orange{color:#e78913;background:#fff7e8}.stat-value{font-size:29px;font-weight:800;line-height:1}.stat-label{color:#66758a;font-size:13px;margin-top:8px}.stat-trend{color:var(--green);font-size:11px;font-weight:700;margin-left:5px}.stat-trend.muted{color:#8a94a6;font-weight:500}
		.dashboard-grid{flex:1;display:grid;grid-template-columns:minmax(0,2.3fr) minmax(320px,1fr);gap:28px;align-items:stretch}.panel{overflow:hidden;display:flex;flex-direction:column}.panel-header{display:flex;align-items:center;justify-content:space-between;padding:24px 26px 17px}.panel-title{display:flex;align-items:center;gap:10px;font-size:16px;font-weight:800}.panel-title svg{width:20px;height:20px;color:var(--red)}.panel-subtitle{color:var(--muted);font-size:12px}.panel-link{color:var(--red);font-size:12px;font-weight:700}.panel-link:hover{color:var(--red-dark)}.tabs{display:flex;gap:8px;padding:0 26px 17px;border-bottom:1px solid #f0f2f5}.tab{border:0;background:#f3f6f9;border-radius:7px;color:#7b8797;cursor:pointer;padding:9px 14px;font-size:11px}.tab.active{color:var(--teal);background:#e8faf6;font-weight:700}.policy-table{width:100%;border-collapse:collapse;table-layout:fixed;flex:1}.policy-table th{color:#8290a2;font-size:10px;font-weight:700;letter-spacing:.05em;padding:16px;text-align:left;text-transform:uppercase}.policy-table td{border-top:1px solid #f2f4f6;color:#536277;font-size:12px;padding:20px 16px;vertical-align:middle}.policy-table th:first-child,.policy-table td:first-child{padding-left:26px;width:27%}.policy-table th:nth-child(2){width:15%}.policy-table th:nth-child(3){width:12%}.policy-table th:nth-child(4){width:22%}.policy-name{color:var(--ink);font-size:13px;font-weight:700}.policy-copy{color:#8a96a6;display:block;font-size:11px;line-height:1.4;margin-top:4px}.type-pill,.status-pill{display:inline-block;border-radius:20px;font-size:11px;font-weight:700;padding:6px 10px}.type-pill{color:#3276cb;background:#edf5ff}.type-pill.purple{color:#8741c6;background:#f6edff}.type-pill.orange{color:#ca8110;background:#fff6e6}.status-pill{color:#07966c;background:#eafaf4}.policy-actions{display:flex;align-items:center;gap:14px;color:#91a0b1}.policy-actions svg{width:15px;height:15px}
		.side-stack{display:grid;gap:28px;grid-template-rows:auto 1fr}.side-stack .panel{height:100%}.status-list,.activity-list{padding:4px 26px 20px;flex:1;display:flex;flex-direction:column}.status-row{display:flex;align-items:center;justify-content:space-between;border-top:1px solid #f1f3f5;padding:18px 0;color:#536277;font-size:12px;flex:1}.online{color:var(--green);display:inline-flex;align-items:center;gap:5px;font-size:11px;font-weight:700}.online:before{content:'';width:6px;height:6px;border-radius:50%;background:var(--green)}.activity{display:grid;grid-template-columns:26px 1fr auto;gap:10px;align-items:start;border-top:1px solid #f1f3f5;padding:16px 0;flex:1}.activity-icon{width:26px;height:26px;display:grid;place-items:center;border-radius:7px;color:var(--teal);background:#eafbf7}.activity-icon svg{width:14px;height:14px}.activity-title{color:#4b5b70;font-size:12px;font-weight:600}.activity-copy{color:#95a0ae;font-size:11px;margin-top:4px}.activity-time{color:#78879a;font-size:11px;text-align:right;white-space:nowrap}.compliance{display:flex;align-items:center;gap:13px;background:#edf7ff;border:1px solid #dcecff;border-radius:12px;margin-top:24px;padding:17px 20px}.compliance-icon{width:34px;height:34px;display:grid;place-items:center;border-radius:8px;background:#2f7fe7;color:#fff;flex-shrink:0}.compliance-icon svg{width:19px}.compliance strong{display:block;color:#225a9c;font-size:11px}.compliance p{color:#66809d;font-size:10px;line-height:1.4;margin:4px 0 0}.learn-more{margin-left:auto;border:1px solid #add5fb;border-radius:7px;color:#2f7fe7;background:#fff;font-size:10px;padding:8px 12px;white-space:nowrap}
		@media(min-width:1700px){.content{padding:44px 72px 64px}.stats{gap:28px}.stat-card{padding:28px 30px;min-height:140px}.stat-icon{width:54px;height:54px}.stat-value{font-size:32px}.dashboard-grid{gap:32px}.panel-header{padding:28px 30px 18px}.policy-table td{padding:22px 18px}}
		@media(max-width:1100px){.sidebar{width:220px;min-width:220px}.main{margin-left:220px}.content{padding-left:24px;padding-right:24px}.stats{grid-template-columns:repeat(2,1fr)}.dashboard-grid{grid-template-columns:minmax(0,1.6fr) minmax(280px,.9fr);gap:18px}}
		@media(max-width:900px){.dashboard-grid{grid-template-columns:1fr}}
		@media(max-width:620px){.sidebar{display:none}.main{margin-left:0}.topbar{height:58px;padding:0 15px}.search{width:210px}.content{padding:22px 14px 34px}.page-heading{gap:12px}.date-note{display:none}.stats{gap:12px}.stat-card{padding:14px;min-height:86px}.policy-table{min-width:680px}.panel.table-panel{overflow-x:auto}.compliance{align-items:flex-start;flex-wrap:wrap}.learn-more{margin-left:45px}}
	</style>
</head>
<body>
	<div class="admin-shell">
		<aside class="sidebar">
			<div class="brand"><span class="brand-mark">+</span><div><span class="brand-name">TeleCare</span><span class="brand-role">SUPER ADMIN</span></div></div>
			<nav class="sidebar-nav">
				<div class="nav-label">Main Menu</div>
				<a class="nav-link active" href="dashboard.php"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path d="M3 11.5 12 4l9 7.5M5 10v10h14V10M9 20v-5h6v5"/></svg>Dashboard</a>
				<div class="nav-group"><div class="nav-label">System Management</div>
					<a class="nav-link" href="../admin/Users.php"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></svg>Users</a>
					<a class="nav-link" href="../admin/assignments.php"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path d="M4 21V5a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v16M4 21h16M8 7h2M14 7h2M8 11h2M14 11h2M8 15h2M14 15h2"/></svg>Clinics</a>
					<a class="nav-link" href="../admin/dashboard.php"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path d="M4 4h16v13H4zM8 21h8M12 17v4"/></svg>Consultations</a>
					<a class="nav-link" href="../admin/prices.php"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path d="M3 7h18M5 7v12h14V7M8 4h8M9 11h6M9 15h4"/></svg>Payments</a>
					<a class="nav-link" href="../admin/dashboard.php"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path d="M4 19V5M4 19h16M8 16v-3M12 16V8M16 16v-5"/></svg>Reports</a>
				</div>
				<div class="nav-group"><div class="nav-label">Legal &amp; Compliance</div>
					<a class="nav-link" href="#policies"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path d="M6 3h9l3 3v15H6zM9 12h6M9 16h6M9 8h3"/></svg>Legal Policies</a>
					<a class="nav-link" href="#activity"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>Audit Logs</a>
					<a class="nav-link" href="#status"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path d="M12 3 4 6v5c0 5 3.5 8.5 8 10 4.5-1.5 8-5 8-10V6zM9 12l2 2 4-4"/></svg>System Settings</a>
				</div>
			</nav>
		</aside>
		<main class="main">
			<header class="topbar"><label class="search"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input type="search" placeholder="Search anything..." aria-label="Search dashboard"></label><div class="top-actions"><div class="notification" aria-label="Notifications"><b>3</b><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg></div><div class="profile"><span class="profile-avatar">SA</span><div><strong>Super Admin</strong><small>System Administrator</small></div></div></div></header>
			<section class="content">
				<div class="page-heading"><div><h1>Welcome, Super Admin!</h1><p class="subtitle">Manage the system's legal policies, monitor platform activity, and ensure compliance.</p></div><div class="date-note"><strong>September 5, 2026</strong>Keep the platform secure and compliant.</div></div>
				<div class="stats">
					<div class="stat-card"><span class="stat-icon blue"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path d="M6 3h9l3 3v15H6zM9 12h6M9 16h4M9 8h3"/></svg></span><div><div class="stat-value">4</div><div class="stat-label">Active Policies</div></div></div>
					<div class="stat-card"><span class="stat-icon teal"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><circle cx="9" cy="8" r="3"/><path d="M3 20a6 6 0 0 1 12 0M16 11a3 3 0 0 1 5 2.2M17 20a5 5 0 0 0-1.5-3.6"/></svg></span><div><div class="stat-value">4,321 <span class="stat-trend">Total Users</span></div><div class="stat-label"><span class="stat-trend">12%</span> from last month</div></div></div>
					<div class="stat-card"><span class="stat-icon purple"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path d="M4 21V5a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v16M4 21h16M8 7h2M14 7h2M8 11h2M14 11h2M8 15h2M14 15h2"/></svg></span><div><div class="stat-value">12 <span class="stat-trend muted">Clinics</span></div><div class="stat-label"><span class="stat-trend">2</span> new this month</div></div></div>
					<div class="stat-card"><span class="stat-icon orange"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4M16 3v4M4 10h16"/></svg></span><div><div class="stat-value">1,248 <span class="stat-trend muted">Appointments</span></div><div class="stat-label"><span class="stat-trend">18%</span> from last month</div></div></div>
				</div>
				<div class="dashboard-grid">
					<section class="panel table-panel" id="policies"><div class="panel-header"><div><div class="panel-title"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path d="M6 3h9l3 3v15H6zM9 12h6M9 16h4M9 8h3"/></svg>Legal Policies</div><div class="panel-subtitle">Manage the legal documents and policies used in the system.</div></div><a class="panel-link" href="#policies">+ Add New Policy</a></div><div class="tabs"><button class="tab active" type="button">All Policies</button><button class="tab" type="button">Data &amp; Privacy</button><button class="tab" type="button">Terms &amp; Agreements</button><button class="tab" type="button">Payments</button></div><table class="policy-table"><thead><tr><th>Title</th><th>Type</th><th>Version</th><th>Last Updated</th><th>Status</th><th>Actions</th></tr></thead><tbody>
						<tr><td><span class="policy-name">Data Policy</span><span class="policy-copy">Guidelines for data collection, usage, and protection.</span></td><td><span class="type-pill">Data &amp; Privacy</span></td><td>v1.2</td><td>Aug 15, 2026<span class="policy-copy">by Super Admin</span></td><td><span class="status-pill">Published</span></td><td><span class="policy-actions"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path d="M2 12s3-5 10-5 10 5 10 5-3 5-10 5-10-5-10-5Z"/><circle cx="12" cy="12" r="2"/></svg><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path d="M12 20h9M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4Z"/></svg></span></td></tr>
						<tr><td><span class="policy-name">Privacy Policy</span><span class="policy-copy">Details on how user information is collected, used, and secured.</span></td><td><span class="type-pill">Data &amp; Privacy</span></td><td>v1.3</td><td>Aug 10, 2026<span class="policy-copy">by Super Admin</span></td><td><span class="status-pill">Published</span></td><td><span class="policy-actions"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path d="M2 12s3-5 10-5 10 5 10 5-3 5-10 5-10-5-10-5Z"/><circle cx="12" cy="12" r="2"/></svg><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path d="M12 20h9M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4Z"/></svg></span></td></tr>
						<tr><td><span class="policy-name">Terms of Use and Agreement</span><span class="policy-copy">Rules and conditions for using the platform.</span></td><td><span class="type-pill purple">Terms &amp; Agreements</span></td><td>v1.1</td><td>Jul 28, 2026<span class="policy-copy">by Super Admin</span></td><td><span class="status-pill">Published</span></td><td><span class="policy-actions"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path d="M2 12s3-5 10-5 10 5 10 5-3 5-10 5-10-5-10-5Z"/><circle cx="12" cy="12" r="2"/></svg><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path d="M12 20h9M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4Z"/></svg></span></td></tr>
						<tr><td><span class="policy-name">Payment Policy</span><span class="policy-copy">Policies for payments, refunds, and transactions.</span></td><td><span class="type-pill orange">Payments</span></td><td>v1.0</td><td>Jul 20, 2026<span class="policy-copy">by Super Admin</span></td><td><span class="status-pill">Published</span></td><td><span class="policy-actions"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path d="M2 12s3-5 10-5 10 5 10 5-3 5-10 5-10-5-10-5Z"/><circle cx="12" cy="12" r="2"/></svg><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path d="M12 20h9M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4Z"/></svg></span></td></tr>
					</tbody></table></section>
					<div class="side-stack"><section class="panel" id="status"><div class="panel-header"><div class="panel-title"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path d="m12 3 8 4v5c0 4.5-3.5 7.8-8 9-4.5-1.2-8-4.5-8-9V7z"/><path d="m9 12 2 2 4-4"/></svg>System Status</div><a href="#status" class="panel-link">View Details</a></div><div class="status-list"><div class="status-row">AI Service <span class="online">Online</span></div><div class="status-row">Medical OCR <span class="online">Online</span></div><div class="status-row">Payment Gateway <span class="online">Online</span></div><div class="status-row">Email Service <span class="online">Online</span></div><div class="status-row">Database <span class="online">Online</span></div></div></section>
						<section class="panel" id="activity"><div class="panel-header"><div class="panel-title"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>Recent Activity</div><a href="#activity" class="panel-link">View All</a></div><div class="activity-list"><div class="activity"><span class="activity-icon"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path d="M6 3h9l3 3v15H6zM9 12h6"/></svg></span><div><div class="activity-title">Policy updated</div><div class="activity-copy">Privacy Policy (v1.3)</div></div><time class="activity-time">Aug 10, 2026<br>10:42 AM</time></div><div class="activity"><span class="activity-icon"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path d="m5 12 4 4L19 6"/></svg></span><div><div class="activity-title">Policy published</div><div class="activity-copy">Data Policy (v1.2)</div></div><time class="activity-time">Aug 8, 2026<br>02:15 PM</time></div><div class="activity"><span class="activity-icon"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path d="M12 5v14M5 12h14"/></svg></span><div><div class="activity-title">New admin created</div><div class="activity-copy">Maria Dela Cruz</div></div><time class="activity-time">Aug 5, 2026<br>09:40 AM</time></div><div class="activity"><span class="activity-icon"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path d="M4 19V5M4 19h16M8 16v-3M12 16V8M16 16v-5"/></svg></span><div><div class="activity-title">Clinic registered</div><div class="activity-copy">North Caloocan Medical Center</div></div><time class="activity-time">Aug 3, 2026<br>11:22 AM</time></div></div></section></div>
				</div>
			</section>
		</main>
	</div>
</body>
</html>