<?php
// Frontend-only Legal Policies screen. Actions are handled by assets/js/js/app.js.
$page_title = 'Legal Policies';
$active_nav = 'legal_policies';
$breadcrumbs = [['label' => 'Dashboard', 'href' => 'dashboard.php'], ['label' => 'Legal Policies']];
$header_icon = '<svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path d="M6 3h9l3 3v15H6zM9 12h6M9 16h6M9 8h3"/></svg>';
$heading = 'Legal Policies';
$subtitle = "Manage the system's legal documents and ensure compliance with applicable laws and regulations.";
$header_actions = '<button type="button" class="btn btn-secondary" data-open-modal="modal-workflow-guide">Workflow Guide</button><a href="edit_policy.php" class="btn btn-primary">+ Create New Policy</a>';
require_once 'includes/header.php';
?>
<div class="panel" style="margin-bottom:24px;">
	<div style="padding:22px 24px 0;display:flex;justify-content:space-between;align-items:center;gap:16px;flex-wrap:wrap;">
		<div class="tabline" data-target="#policiesTable"><button type="button" class="active" data-filter="all">All Policies</button><button type="button" data-filter="Data &amp; Privacy">Data &amp; Privacy</button><button type="button" data-filter="Terms &amp; Agreements">Terms &amp; Agreements</button><button type="button" data-filter="Payments">Payments</button></div>
		<label class="search" style="width:240px;"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input type="search" id="policySearch" placeholder="Search policies..."></label>
	</div>
	<div class="panel-body">
		<table class="data-table" id="policiesTable"><thead><tr><th>Title</th><th>Type</th><th>Version</th><th>Last Updated</th><th>Status</th><th>Actions</th></tr></thead><tbody>
			<tr data-type="Data &amp; Privacy"><td><div class="row-title"><span class="row-icon" style="background:var(--blue-light);color:var(--blue);"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path d="M6 3h9l3 3v15H6zM9 12h6M9 16h6M9 8h3"/></svg></span><div><span class="policy-name">Data Policy</span><span class="policy-copy">Guidelines for data collection, usage, and protection.</span></div></div></td><td><span class="pill pill-blue">Data &amp; Privacy</span></td><td>v1.2</td><td>Aug 15, 2026<span class="updated-by">by Super Admin</span></td><td><span class="pill pill-green">Published</span></td><td><div class="row-actions"><a class="icon-action" href="policy_history.php?id=1" title="View version history">View</a><a class="icon-action" href="edit_policy.php?id=1" title="Edit policy">Edit</a><button type="button" class="icon-action kebab-btn" title="More actions">...</button><div class="dropdown-menu"><button type="button" onclick="window.location='edit_policy.php?id=1'">Edit policy</button><button type="button" onclick="window.location='policy_history.php?id=1'">Version history</button><button type="button" class="danger" data-open-modal="modal-delete-policy" data-fill="Data Policy">Delete policy</button></div></div></td></tr>
			<tr data-type="Data &amp; Privacy"><td><div class="row-title"><span class="row-icon" style="background:var(--blue-light);color:var(--blue);"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path d="M6 3h9l3 3v15H6zM9 12h6M9 16h6M9 8h3"/></svg></span><div><span class="policy-name">Privacy Policy</span><span class="policy-copy">Details on how user information is collected, used, and secured.</span></div></div></td><td><span class="pill pill-blue">Data &amp; Privacy</span></td><td>v1.3</td><td>Aug 10, 2026<span class="updated-by">by Super Admin</span></td><td><span class="pill pill-green">Published</span></td><td><div class="row-actions"><a class="icon-action" href="policy_history.php?id=2">View</a><a class="icon-action" href="edit_policy.php?id=2">Edit</a></div></td></tr>
			<tr data-type="Terms &amp; Agreements"><td><div class="row-title"><span class="row-icon" style="background:var(--purple-light);color:var(--purple);">DOC</span><div><span class="policy-name">Terms of Use and Agreement</span><span class="policy-copy">Rules and conditions for using the platform.</span></div></div></td><td><span class="pill pill-purple">Terms &amp; Agreements</span></td><td>v1.1</td><td>Jul 28, 2026<span class="updated-by">by Super Admin</span></td><td><span class="pill pill-green">Published</span></td><td><div class="row-actions"><a class="icon-action" href="policy_history.php?id=3">View</a><a class="icon-action" href="edit_policy.php?id=3">Edit</a></div></td></tr>
			<tr data-type="Payments"><td><div class="row-title"><span class="row-icon" style="background:var(--orange-light);color:var(--orange);">PAY</span><div><span class="policy-name">Payment Policy</span><span class="policy-copy">Policies for payments, refunds, and transactions.</span></div></div></td><td><span class="pill pill-orange">Payments</span></td><td>v1.0</td><td>Jul 20, 2026<span class="updated-by">by Super Admin</span></td><td><span class="pill pill-green">Published</span></td><td><div class="row-actions"><a class="icon-action" href="policy_history.php?id=4">View</a><a class="icon-action" href="edit_policy.php?id=4">Edit</a></div></td></tr>
		</tbody></table>
		<div class="pagination-bar"><span>Showing 4 of 4 active policies</span><div class="pager"><button type="button" disabled>Previous</button><button type="button" class="active">1</button><button type="button">Next</button></div></div>
	</div>
</div>
<div class="panel steps-panel"><div class="panel-header"><div><h3>Policy Management Process</h3><p>Complete workflow cycle for creating, testing, and managing legally compliant documents.</p></div><span class="pill pill-green">System-wide Enforced</span></div><div class="steps-grid"><div class="step-card"><div class="step-title">1. Create</div><div class="step-desc">Add new policy and initialize as Draft.</div></div><div class="step-card"><div class="step-title">2. Edit</div><div class="step-desc">Modify content, clauses, or targeting.</div></div><div class="step-card"><div class="step-title">3. Preview</div><div class="step-desc">Review the end-user viewport.</div></div><div class="step-card active"><div class="step-title">4. Publish</div><div class="step-desc">Make policy live across client portals.</div></div><div class="step-card"><div class="step-title">5. Manage</div><div class="step-desc">Audit, restore, or archive versions.</div></div></div></div>
<div class="modal-overlay" id="modal-delete-policy"><div class="modal-box"><h3 class="modal-title">Delete this policy?</h3><p class="modal-text"><strong data-fill-target>this policy</strong> will be removed from this frontend preview.</p><div class="modal-actions"><button type="button" class="btn btn-secondary" data-close-modal="modal-delete-policy">Cancel</button><button type="button" class="btn btn-primary" data-confirm-action="Policy removed from preview.">Remove</button></div></div></div>
<div class="modal-overlay" id="modal-workflow-guide"><div class="modal-box"><h3 class="modal-title">How the policy workflow works</h3><p class="modal-text">Create, edit, preview, publish, and manage policy versions using this frontend prototype.</p><div class="modal-actions"><button type="button" class="btn btn-primary btn-block" data-close-modal="modal-workflow-guide">Got it</button></div></div></div>
<?php require_once 'includes/footer.php'; ?>
